spring:
  application.name: scrooge
  jackson.serialization:
    write_dates_as_timestamps: false
    indent_output: true
#  data.mongodb:
#    host: localhost
#    port: 27017

management.security.enabled: true